pylint fixes for CI (#209)
* fixed pylint errors

ERROR: plugins/module_utils/network/ftd/configuration.py:362:12:
 self-assigning-variable: Assigning the same variable 'obj' to itself
ERROR: plugins/modules/network/cloudengine/ce_static_route_bfd.py:552:8:
 self-assigning-variable: Assigning the same variable 'value' to itself
ERROR: plugins/modules/network/radware/vdirect_runnable.py:261:0:
 unnecessary-comprehension: Unnecessary use of a comprehension
ERROR: plugins/netconf/ce.py:125:0: unnecessary-comprehension: Unnecessary use of a comprehension
ERROR: plugins/netconf/ce.py:126:0: unnecessary-comprehension: Unnecessary use of a comprehension
ERROR: plugins/netconf/sros.py:87:0: unnecessary-comprehension: Unnecessary use of a comprehension
ERROR: plugins/netconf/sros.py:88:0: unnecessary-comprehension: Unnecessary use of a comprehension

* Apply suggestions from code review

Co-authored-by: Felix Fontein <felix@fontein.de>

Co-authored-by: Felix Fontein <felix@fontein.de>
(cherry picked from commit 14da06020a5ac245d33750bc42295e12b39095e0)